debug: true
spring:
  application:
    name: auth-server
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

server:
  port: 8081
  servlet:
    context-path: /auth
user:
  oauth:
    clientId: R2dpxQ3vPrtfgF72
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: http://localhost:8082/login/oauth2/code/
    user:
      username: admin
      password: admin

