
spring:
  application:
    name: auth-server
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/userlearning?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

server:
  port: 8081
  servlet:
    context-path: /auth
    
