server:
  port: 8082
  servlet:
    session:
      cookie:
        name: UISESSION

logging:
  level:
    root: info
spring:
  application:
    name: user-service
  security:
    oauth2:
      client:
        registration:
          userservice: # The registration Id which you need to pass in /oauth2/authorization/auth-server
            client-id: clientapp
            client-secret: 123456
            client-name: Auth Server
            scope: user_info
            redirect-uri: http://localhost:8082/login/oauth2/code/userservice
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: lspace-auth-server
        provider:
          lspace-auth-server:
            token-uri: http://localhost:4444/auth/oauth/token
            authorization-uri: http://localhost:4444/auth/oauth/authorize
            user-info-uri: http://localhost:4444/auth/userInfo
            user-name-attribute: name
